steps:

- task: dotNetCoreCLI@2
  inputs:
    command: restore
    projects: "**/*.csproj"
  displayName: dotnet restore

- task: dotNetCoreCLI@2
  inputs:
    command: build
    projects: "**/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

- task: Npm@1
  displayName: "installing angular-cli"
  inputs:
    command: "custom"
    verbose: "false"
    customCommand: "install @angular/cli@1.6.1 -g"

- task: Npm@1
  displayName: npm install
  inputs:
    command: install
    
- task: CmdLine@1
  displayName: "angular build"
  inputs:
    filename: "ng"
    arguments: "build --prod"

- task: dotNetCoreCLI@2
  inputs:
    command: test 
    projects: "**/*Tests/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

- task: dotNetCoreCLI@2
  inputs:
    command: publish
    arguments: --configuration release --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
    publishWebProjects: true
  displayName: dotnet publish

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
  displayName: Publish the artifacts
